version: '3.8'

services:
  # Base de Datos (MySQL según tus logs)
  db:
    image: mysql:8.0
    container_name: db_backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sistema_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - backend_net

  # Microservicio de Ventas
  ventas:
    image: rodrigoruiz123/ms-ventas:latest
    container_name: ms_ventas
    depends_on:
      - db
    # AQUÍ ESTÁ LA SOLUCIÓN: Pasamos las variables que Java está gritando
    environment:
      DB_ENDPOINT: db
      DB_PORT: 3306
      DB_NAME: sistema_db
      DB_USER: user
      DB_PASSWORD: password
    networks:
      - backend_net

  # Microservicio de Despachos
  despachos:
    image: rodrigoruiz123/ms-despachos:latest
    container_name: ms_despachos
    depends_on:
      - db
    environment:
      DB_ENDPOINT: db
      DB_PORT: 3306
      DB_NAME: sistema_db
      DB_USER: user
      DB_PASSWORD: password
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  mysql_data: